# Generated by Django 5.2 on 2025-08-25 11:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networkentity",
            name="product",
        ),
        migrations.RemoveField(
            model_name="networkentity",
            name="supplier",
        ),
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "product_model",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("product_launch_date", models.DateField(blank=True, null=True)),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Розничная сеть"),
                            (2, "Индивидуальный предприниматель"),
                        ],
                        editable=False,
                        help_text="Уровень в цепочке: 0 — завод, 1 — розничная сеть, 2 — ИП",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Предыдущий по иерархии узел (поставщик).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="network.networknode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сеть (узел)",
                "verbose_name_plural": "Сеть",
            },
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="NetworkEntity",
        ),
    ]
