# Generated by Django 5.2 on 2025-08-26 06:04

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_remove_networkentity_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Страна"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Город"),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Улица"),
                ),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=20, null=True, verbose_name="Номер дома"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(db_index=True, max_length=255)),
                (
                    "debt",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_objects",
                        to="network.supplier",
                    ),
                ),
            ],
        ),
    ]
