# Generated by Django 5.2 on 2025-08-27 09:18

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_supplier_networkobject"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="debt",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
    ]
