# Generated by Django 5.2 on 2025-09-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("street", models.CharField(max_length=255)),
                ("house_number", models.CharField(max_length=10)),
            ],
        ),
    ]
