# Generated by Django 5.2 on 2025-09-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название категории")),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="products", to="network.category"),
        ),
    ]
